
# This file is used to configure your Supabase project.
# It's very minimal at the moment and uses default values.
# You can find more information here: https://supabase.com/docs/guides/functions/edge-runtime

project_id = "zgdrcbdrmnhvfzygyecx"

[functions.process-places-data]
verify_jwt = true

[functions.generate-personality-insights]
verify_jwt = true
