// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgdrcbdrmnhvfzygyecx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZHJjYmRybW5odmZ6eWd5ZWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Nzg3NjQsImV4cCI6MjA1OTQ1NDc2NH0.ZKWH4PfKAGNC7MgseDQkf7FulljpiOjHHO21neLKlPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);